# Generated by Django 3.2.9 on 2021-12-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211110_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например Заголовок: Сегодня все пришли на урок', max_length=255, verbose_name='Название')),
                ('image', models.ImageField(help_text='Загружайте только jpg и png формат изображении', upload_to='partners', verbose_name='Лого')),
                ('link', models.CharField(blank=True, help_text='Например: https://www.site.com/ или https://www.instagram.com/edzn_bey/?hl=ru', max_length=255, null=True, verbose_name='ссылка на страницу партнера')),
            ],
            options={
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
