# Generated by Django 3.2.9 on 2021-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Соцсети и Мессенджеры'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='icon_socmedia',
            field=models.CharField(choices=[('odnoklassniki', 'odnoklassniki'), ('instagram', 'instagram'), ('facebook', 'facebook'), ('linkedin', 'linkedin'), ('telegram', 'telegram'), ('whatsapp', 'whatsapp'), ('envelope', 'envelope'), ('envelope', 'envelope'), ('twitter', 'twitter'), ('youtube', 'youtube'), ('skype', 'skype'), ('vk', 'vk')], default=1, max_length=100, verbose_name='выбери что будет'),
            preserve_default=False,
        ),
    ]
