# Generated by Django 3.2.9 on 2021-12-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20211202_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon_socmedia',
            field=models.CharField(choices=[('odnoklassniki', 'odnoklassniki'), ('instagram', 'instagram'), ('facebook', 'facebook'), ('linkedin', 'linkedin'), ('telegram', 'telegram'), ('whatsapp', 'whatsapp'), ('evernote', 'evernote'), ('twitter', 'twitter'), ('youtube', 'youtube'), ('skype', 'skype'), ('vk', 'vk')], max_length=100, verbose_name='выбери что будет'),
        ),
    ]
