# Generated by Django 3.2.9 on 2021-12-13 14:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211121_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_page',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Страница 'О нас'"),
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_page',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Страница 'Контакты'"),
        ),
    ]
